##
## Makefile : for Static/Shared/Dynamic Library Programming
##
##		Kim Soo Hyun(@")
##

PLATFORM =
CC = $(PLATFORM)gcc

all : static shared

static : 
	@echo "Static Library Build..."
	.......

shared :
	@echo "Shared Library Build..."
	.......

clean :
	...........

clean_static :
	............
clean_shared :
	............
