##
## Makefile : for Static/Shared/Dynamic Library Programming
##
##		Kim Soo Hyun(@")
##

PLATFORM = 

INC_PATH = ../include
CC = $(PLATFORM)gcc
CFLAGS = -Wall -O2 -I$(INC_PATH)
LIB_PATH_STATIC = ../libStatic
LIB_PATH_SHARED = ../libShared

APP = app
APP_ALL = app_static app_shared

all : $(APP_ALL)

.............